# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/03_andrey/py_progects/QtTutor/ui_to_py/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 160)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 160))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.convert_button = QtWidgets.QPushButton(self.frame)
        self.convert_button.setObjectName("convert_button")
        self.gridLayout_2.addWidget(self.convert_button, 4, 0, 1, 2)
        self.disigner_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disigner_label.sizePolicy().hasHeightForWidth())
        self.disigner_label.setSizePolicy(sizePolicy)
        self.disigner_label.setObjectName("disigner_label")
        self.gridLayout_2.addWidget(self.disigner_label, 0, 0, 1, 1)
        self.disigner_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.disigner_lineEdit.setObjectName("disigner_lineEdit")
        self.gridLayout_2.addWidget(self.disigner_lineEdit, 1, 0, 1, 1)
        self.disigner_button = QtWidgets.QPushButton(self.frame)
        self.disigner_button.setMinimumSize(QtCore.QSize(60, 0))
        self.disigner_button.setObjectName("disigner_button")
        self.gridLayout_2.addWidget(self.disigner_button, 1, 1, 1, 1)
        self.qt_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.qt_lineEdit.setObjectName("qt_lineEdit")
        self.gridLayout_2.addWidget(self.qt_lineEdit, 3, 0, 1, 1)
        self.qt_button = QtWidgets.QPushButton(self.frame)
        self.qt_button.setObjectName("qt_button")
        self.gridLayout_2.addWidget(self.qt_button, 3, 1, 1, 1)
        self.qt_label = QtWidgets.QLabel(self.frame)
        self.qt_label.setObjectName("qt_label")
        self.gridLayout_2.addWidget(self.qt_label, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ui to py converter"))
        self.convert_button.setText(_translate("MainWindow", "Convert ui to python file"))
        self.disigner_label.setText(_translate("MainWindow", "Qt Designer file (*.ui):"))
        self.disigner_button.setText(_translate("MainWindow", "Add path"))
        self.qt_button.setText(_translate("MainWindow", "Add path"))
        self.qt_label.setText(_translate("MainWindow", "Output python file:"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About program"))
