# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/03_andrey/py_progects/Qt_projects/tetris/tetris_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(232, 422)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 232, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actiongame_level = QtWidgets.QAction(MainWindow)
        self.actiongame_level.setObjectName("actiongame_level")
        self.actionmiddle = QtWidgets.QAction(MainWindow)
        self.actionmiddle.setObjectName("actionmiddle")
        self.actionHard = QtWidgets.QAction(MainWindow)
        self.actionHard.setObjectName("actionHard")
        self.actionAbout_program = QtWidgets.QAction(MainWindow)
        self.actionAbout_program.setObjectName("actionAbout_program")
        self.actionabout_program = QtWidgets.QAction(MainWindow)
        self.actionabout_program.setObjectName("actionabout_program")
        self.menu.addAction(self.actiongame_level)
        self.menu.addAction(self.actionmiddle)
        self.menu.addAction(self.actionHard)
        self.menuHelp.addAction(self.actionAbout_program)
        self.menuHelp.addAction(self.actionabout_program)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tetris"))
        self.menu.setTitle(_translate("MainWindow", "Game level"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actiongame_level.setText(_translate("MainWindow", "Easy"))
        self.actionmiddle.setText(_translate("MainWindow", "Middle"))
        self.actionHard.setText(_translate("MainWindow", "Hard"))
        self.actionAbout_program.setText(_translate("MainWindow", "Help"))
        self.actionabout_program.setText(_translate("MainWindow", "About program"))
